name: publish-kedro-viz
description: This is a GitHub action to publish kedro viz static website on GitHub Pages
author: kedro-viz

branding:
  icon: share
  color: yellow

inputs:
  project_path:
    description: "Set your Kedro-project path to build the Kedro-Viz artifacts."
    required: false
    default: "."
  include_hooks:
    description: "Set whether to include hooks while creating your Kedro-project build artifacts."
    required: false
    default: false
  telemetry_consent:
    description: "Set your consent if you would like to participate in Kedro-Telemetry. Defaults to false"
    required: false
    default: false
  python_manager:
    description: "Set the Python package manager to use ('pip' or 'uv'). Defaults to 'pip'"
    required: false
    default: "pip"

runs:
  using: "composite"
  steps:
    - name: Install Kedro-Viz
      run: |
        if [ "${{ inputs.python_manager }}" = "uv" ]; then
          uv add "kedro-viz>=7.1.0"
        else
          python -m pip install --upgrade pip
          python -m pip install "kedro-viz>=7.1.0"
        fi
      shell: bash
    - name: Consent to the use of Kedro-Telemetry
      run: |
        cd ${{ inputs.project_path }}
        echo 'consent: ${{ inputs.telemetry_consent }}' > .telemetry
      shell: bash
    - name: Create build flags
      run: |
        flag=""
        if ${{ inputs.include_hooks }}; then
          flag="$flag --include-hooks"
        fi
        echo "build_flags=$flag" >> $GITHUB_ENV
      shell: bash
    - name: Create build directory
      run: |
        cd ${{ inputs.project_path }}
        if [ "${{ inputs.python_manager }}" = "uv" ]; then
          if !(uv run kedro viz build ${{ env.build_flags }} |& tee /dev/stderr | grep -i -q "Success!"); then
            exit 1
          fi
        else
          if !(kedro viz build ${{ env.build_flags }} |& tee /dev/stderr | grep -i -q "Success!"); then
            exit 1
          fi
        fi
      shell: bash
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        path: "${{ inputs.project_path }}/build"
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
